#!/bin/bash
VENV_NAME=venv/qualify
DATE=$(date +'%Y-%m-%d.%H-%M')

BUILD_DIR=$(pwd)
go build ../gapic-showcase/

verify() {
  name=$1
  msg=$2
  $name --version  >& /dev/null || { echo "Please install $name to continue. $2" ; return 2 ; }  
}

verify python3 || return $?
verify protoc "See https://github.com/protocolbuffers/protobuf/releases" || return $?
verify pip || return $?
verify curl || return $?

export GAPIC_QUALIFY_DIR=${1:-$(mktemp -d -t qualify.${DATE}.XXXXXX)}
pushd ${GAPIC_QUALIFY_DIR} >& /dev/null


VENV_CREATE="python3 -m venv $VENV_NAME"

echo '=== creating venv'  && \
  ${VENV_CREATE} || { python3 -m pip install virtualenv && ${VENV_ACTIVATE} ; } && \
  echo "=== activating venv"  && \
  . ${VENV_NAME}/bin/activate && \
  echo "=== installing pip" && \
  pip install sample-tester && \
  echo "=== installing showcase" && \
  mv ${BUILD_DIR}/gapic-showcase . && \
  export PATH=$(pwd):${PATH}


popd >& /dev/null
echo -e "\nInstalled in: ${GAPIC_QUALIFY_DIR}"

# To get the Go plugin to work:
#
# VC_PROTO_PATH=/home/vchudnov/Work/ACTools/gapic-showcase/acceptance/passing
# GO_PLUGIN_DIR=/tmp/goinstall
# mkdir ${GO_PLUGIN_DIR}
# GOPATH=${GO_PLUGIN_DIR} go install github.com/googleapis/gapic-generator-go/cmd/protoc-gen-go_gapic
# protoc --go_gapic_out ./gen --go_gapic_opt 'go-gapic-package=cloud.google.com/go/showcase/apiv1beta1;showcase' --plugin=${GO_PLUGIN_DIR}/bin/protoc-gen-go_gapic --proto_path=${VC_PROTO_PATH} ${VC_PROTO_PATH}/echo.proto
