#!/bin/bash
VENV_NAME=venv/qualify
DATE=$(date +'%Y-%m-%d.%H-%M')

BUILD_DIR=$(pwd)
go build ../gapic-showcase/

verify() {
  name=$1
  $name --version  >& /dev/null || { echo "Please install $name to continue" ; return 2 ; }  
}

verify python3 || return $?
# verify protoc || return $?
verify pip || return $?
verify curl || return $?

export GAPIC_QUALIFY_DIR=${1:-$(mktemp -d -t qualify.${DATE}.XXXXXX)}
pushd ${GAPIC_QUALIFY_DIR} >& /dev/null


VENV_CREATE="python3 -m venv $VENV_NAME"

echo '=== creating venv'  && \
  ${VENV_CREATE} || { python3 -m pip install virtualenv && ${VENV_ACTIVATE} ; } && \
  echo "=== activating venv"  && \
  . ${VENV_NAME}/bin/activate && \
  echo "=== installing pip" && \
  pip install sample-tester && \
  echo "=== installing showcase" && \
  mv ${BUILD_DIR}/gapic-showcase . && \
  export PATH=$(pwd):${PATH}


popd >& /dev/null
echo -e "\nInstalled in: ${GAPIC_QUALIFY_DIR}"

