// Code generated by protoc-gen-go. DO NOT EDIT.
// source: google/showcase/v1alpha3/messaging.proto

package genproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	longrunning "google.golang.org/genproto/googleapis/longrunning"
	errdetails "google.golang.org/genproto/googleapis/rpc/errdetails"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Room struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName          string               `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{0}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Room) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Room) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Room) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Room) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type CreateRoomRequest struct {
	Room                 *Room    `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{1}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type GetRoomRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoomRequest) Reset()         { *m = GetRoomRequest{} }
func (m *GetRoomRequest) String() string { return proto.CompactTextString(m) }
func (*GetRoomRequest) ProtoMessage()    {}
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{2}
}

func (m *GetRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoomRequest.Unmarshal(m, b)
}
func (m *GetRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoomRequest.Marshal(b, m, deterministic)
}
func (m *GetRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoomRequest.Merge(m, src)
}
func (m *GetRoomRequest) XXX_Size() int {
	return xxx_messageInfo_GetRoomRequest.Size(m)
}
func (m *GetRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoomRequest proto.InternalMessageInfo

func (m *GetRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateRoomRequest struct {
	Room                 *Room                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateRoomRequest) Reset()         { *m = UpdateRoomRequest{} }
func (m *UpdateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoomRequest) ProtoMessage()    {}
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{3}
}

func (m *UpdateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoomRequest.Unmarshal(m, b)
}
func (m *UpdateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoomRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoomRequest.Merge(m, src)
}
func (m *UpdateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoomRequest.Size(m)
}
func (m *UpdateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoomRequest proto.InternalMessageInfo

func (m *UpdateRoomRequest) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *UpdateRoomRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteRoomRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoomRequest) Reset()         { *m = DeleteRoomRequest{} }
func (m *DeleteRoomRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoomRequest) ProtoMessage()    {}
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{4}
}

func (m *DeleteRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoomRequest.Unmarshal(m, b)
}
func (m *DeleteRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoomRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoomRequest.Merge(m, src)
}
func (m *DeleteRoomRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoomRequest.Size(m)
}
func (m *DeleteRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoomRequest proto.InternalMessageInfo

func (m *DeleteRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListRoomsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoomsRequest) Reset()         { *m = ListRoomsRequest{} }
func (m *ListRoomsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRoomsRequest) ProtoMessage()    {}
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{5}
}

func (m *ListRoomsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoomsRequest.Unmarshal(m, b)
}
func (m *ListRoomsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoomsRequest.Marshal(b, m, deterministic)
}
func (m *ListRoomsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoomsRequest.Merge(m, src)
}
func (m *ListRoomsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRoomsRequest.Size(m)
}
func (m *ListRoomsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoomsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoomsRequest proto.InternalMessageInfo

func (m *ListRoomsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListRoomsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListRoomsResponse struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoomsResponse) Reset()         { *m = ListRoomsResponse{} }
func (m *ListRoomsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRoomsResponse) ProtoMessage()    {}
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{6}
}

func (m *ListRoomsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoomsResponse.Unmarshal(m, b)
}
func (m *ListRoomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoomsResponse.Marshal(b, m, deterministic)
}
func (m *ListRoomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoomsResponse.Merge(m, src)
}
func (m *ListRoomsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRoomsResponse.Size(m)
}
func (m *ListRoomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoomsResponse proto.InternalMessageInfo

func (m *ListRoomsResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func (m *ListRoomsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type Message struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// This will eventually become a User message that will cover add coverage for
	// shared resources.
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*Message_Text
	//	*Message_Image
	Content              isMessage_Content    `protobuf_oneof:"content"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{7}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Text struct {
	Text string `protobuf:"bytes,3,opt,name=text,proto3,oneof"`
}

type Message_Image struct {
	Image []byte `protobuf:"bytes,4,opt,name=image,proto3,oneof"`
}

func (*Message_Text) isMessage_Content() {}

func (*Message_Image) isMessage_Content() {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetText() string {
	if x, ok := m.GetContent().(*Message_Text); ok {
		return x.Text
	}
	return ""
}

func (m *Message) GetImage() []byte {
	if x, ok := m.GetContent().(*Message_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Message) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Message) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Text)(nil),
		(*Message_Image)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_Text:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Text)
	case *Message_Image:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Image)
	case nil:
	default:
		return fmt.Errorf("Message.Content has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 3: // content.text
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Content = &Message_Text{x}
		return true, err
	case 4: // content.image
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Content = &Message_Image{x}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_Text:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Text)))
		n += len(x.Text)
	case *Message_Image:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Image)))
		n += len(x.Image)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateMessageRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Message              *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMessageRequest) Reset()         { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()    {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{8}
}

func (m *CreateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMessageRequest.Unmarshal(m, b)
}
func (m *CreateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMessageRequest.Marshal(b, m, deterministic)
}
func (m *CreateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMessageRequest.Merge(m, src)
}
func (m *CreateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMessageRequest.Size(m)
}
func (m *CreateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMessageRequest proto.InternalMessageInfo

func (m *CreateMessageRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateMessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type GetMessageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageRequest) Reset()         { *m = GetMessageRequest{} }
func (m *GetMessageRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageRequest) ProtoMessage()    {}
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{9}
}

func (m *GetMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageRequest.Unmarshal(m, b)
}
func (m *GetMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageRequest.Marshal(b, m, deterministic)
}
func (m *GetMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageRequest.Merge(m, src)
}
func (m *GetMessageRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageRequest.Size(m)
}
func (m *GetMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageRequest proto.InternalMessageInfo

func (m *GetMessageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateMessageRequest struct {
	Message              *Message              `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateMessageRequest) Reset()         { *m = UpdateMessageRequest{} }
func (m *UpdateMessageRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMessageRequest) ProtoMessage()    {}
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{10}
}

func (m *UpdateMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessageRequest.Unmarshal(m, b)
}
func (m *UpdateMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessageRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessageRequest.Merge(m, src)
}
func (m *UpdateMessageRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMessageRequest.Size(m)
}
func (m *UpdateMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessageRequest proto.InternalMessageInfo

func (m *UpdateMessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *UpdateMessageRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteMessageRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMessageRequest) Reset()         { *m = DeleteMessageRequest{} }
func (m *DeleteMessageRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMessageRequest) ProtoMessage()    {}
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{11}
}

func (m *DeleteMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMessageRequest.Unmarshal(m, b)
}
func (m *DeleteMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMessageRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMessageRequest.Merge(m, src)
}
func (m *DeleteMessageRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMessageRequest.Size(m)
}
func (m *DeleteMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMessageRequest proto.InternalMessageInfo

func (m *DeleteMessageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListMessagesRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMessagesRequest) Reset()         { *m = ListMessagesRequest{} }
func (m *ListMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListMessagesRequest) ProtoMessage()    {}
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{12}
}

func (m *ListMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesRequest.Unmarshal(m, b)
}
func (m *ListMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesRequest.Marshal(b, m, deterministic)
}
func (m *ListMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesRequest.Merge(m, src)
}
func (m *ListMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListMessagesRequest.Size(m)
}
func (m *ListMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesRequest proto.InternalMessageInfo

func (m *ListMessagesRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListMessagesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListMessagesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListMessagesResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextPageToken        string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListMessagesResponse) Reset()         { *m = ListMessagesResponse{} }
func (m *ListMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListMessagesResponse) ProtoMessage()    {}
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{13}
}

func (m *ListMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMessagesResponse.Unmarshal(m, b)
}
func (m *ListMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMessagesResponse.Marshal(b, m, deterministic)
}
func (m *ListMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMessagesResponse.Merge(m, src)
}
func (m *ListMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListMessagesResponse.Size(m)
}
func (m *ListMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMessagesResponse proto.InternalMessageInfo

func (m *ListMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *ListMessagesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type SearchMessagesRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchMessagesRequest) Reset()         { *m = SearchMessagesRequest{} }
func (m *SearchMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchMessagesRequest) ProtoMessage()    {}
func (*SearchMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{14}
}

func (m *SearchMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchMessagesRequest.Unmarshal(m, b)
}
func (m *SearchMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchMessagesRequest.Marshal(b, m, deterministic)
}
func (m *SearchMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchMessagesRequest.Merge(m, src)
}
func (m *SearchMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchMessagesRequest.Size(m)
}
func (m *SearchMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchMessagesRequest proto.InternalMessageInfo

func (m *SearchMessagesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchMessagesMetadata struct {
	RetryInfo            *errdetails.RetryInfo `protobuf:"bytes,1,opt,name=retry_info,json=retryInfo,proto3" json:"retry_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SearchMessagesMetadata) Reset()         { *m = SearchMessagesMetadata{} }
func (m *SearchMessagesMetadata) String() string { return proto.CompactTextString(m) }
func (*SearchMessagesMetadata) ProtoMessage()    {}
func (*SearchMessagesMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{15}
}

func (m *SearchMessagesMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchMessagesMetadata.Unmarshal(m, b)
}
func (m *SearchMessagesMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchMessagesMetadata.Marshal(b, m, deterministic)
}
func (m *SearchMessagesMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchMessagesMetadata.Merge(m, src)
}
func (m *SearchMessagesMetadata) XXX_Size() int {
	return xxx_messageInfo_SearchMessagesMetadata.Size(m)
}
func (m *SearchMessagesMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchMessagesMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_SearchMessagesMetadata proto.InternalMessageInfo

func (m *SearchMessagesMetadata) GetRetryInfo() *errdetails.RetryInfo {
	if m != nil {
		return m.RetryInfo
	}
	return nil
}

type SearchMessagesResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SearchMessagesResponse) Reset()         { *m = SearchMessagesResponse{} }
func (m *SearchMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*SearchMessagesResponse) ProtoMessage()    {}
func (*SearchMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{16}
}

func (m *SearchMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchMessagesResponse.Unmarshal(m, b)
}
func (m *SearchMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchMessagesResponse.Marshal(b, m, deterministic)
}
func (m *SearchMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchMessagesResponse.Merge(m, src)
}
func (m *SearchMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_SearchMessagesResponse.Size(m)
}
func (m *SearchMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchMessagesResponse proto.InternalMessageInfo

func (m *SearchMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type StreamMessagesRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMessagesRequest) Reset()         { *m = StreamMessagesRequest{} }
func (m *StreamMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*StreamMessagesRequest) ProtoMessage()    {}
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{17}
}

func (m *StreamMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMessagesRequest.Unmarshal(m, b)
}
func (m *StreamMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMessagesRequest.Marshal(b, m, deterministic)
}
func (m *StreamMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMessagesRequest.Merge(m, src)
}
func (m *StreamMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_StreamMessagesRequest.Size(m)
}
func (m *StreamMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMessagesRequest proto.InternalMessageInfo

func (m *StreamMessagesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SendMessagesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessagesResponse) Reset()         { *m = SendMessagesResponse{} }
func (m *SendMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessagesResponse) ProtoMessage()    {}
func (*SendMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_14636aef9f8d040f, []int{18}
}

func (m *SendMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessagesResponse.Unmarshal(m, b)
}
func (m *SendMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessagesResponse.Marshal(b, m, deterministic)
}
func (m *SendMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessagesResponse.Merge(m, src)
}
func (m *SendMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessagesResponse.Size(m)
}
func (m *SendMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessagesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Room)(nil), "google.showcase.v1alpha3.Room")
	proto.RegisterType((*CreateRoomRequest)(nil), "google.showcase.v1alpha3.CreateRoomRequest")
	proto.RegisterType((*GetRoomRequest)(nil), "google.showcase.v1alpha3.GetRoomRequest")
	proto.RegisterType((*UpdateRoomRequest)(nil), "google.showcase.v1alpha3.UpdateRoomRequest")
	proto.RegisterType((*DeleteRoomRequest)(nil), "google.showcase.v1alpha3.DeleteRoomRequest")
	proto.RegisterType((*ListRoomsRequest)(nil), "google.showcase.v1alpha3.ListRoomsRequest")
	proto.RegisterType((*ListRoomsResponse)(nil), "google.showcase.v1alpha3.ListRoomsResponse")
	proto.RegisterType((*Message)(nil), "google.showcase.v1alpha3.Message")
	proto.RegisterType((*CreateMessageRequest)(nil), "google.showcase.v1alpha3.CreateMessageRequest")
	proto.RegisterType((*GetMessageRequest)(nil), "google.showcase.v1alpha3.GetMessageRequest")
	proto.RegisterType((*UpdateMessageRequest)(nil), "google.showcase.v1alpha3.UpdateMessageRequest")
	proto.RegisterType((*DeleteMessageRequest)(nil), "google.showcase.v1alpha3.DeleteMessageRequest")
	proto.RegisterType((*ListMessagesRequest)(nil), "google.showcase.v1alpha3.ListMessagesRequest")
	proto.RegisterType((*ListMessagesResponse)(nil), "google.showcase.v1alpha3.ListMessagesResponse")
	proto.RegisterType((*SearchMessagesRequest)(nil), "google.showcase.v1alpha3.SearchMessagesRequest")
	proto.RegisterType((*SearchMessagesMetadata)(nil), "google.showcase.v1alpha3.SearchMessagesMetadata")
	proto.RegisterType((*SearchMessagesResponse)(nil), "google.showcase.v1alpha3.SearchMessagesResponse")
	proto.RegisterType((*StreamMessagesRequest)(nil), "google.showcase.v1alpha3.StreamMessagesRequest")
	proto.RegisterType((*SendMessagesResponse)(nil), "google.showcase.v1alpha3.SendMessagesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessagingClient is the client API for Messaging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagingClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error)
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error)
	UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error)
	DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*Message, error)
	UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*Message, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error)
	SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*longrunning.Operation, error)
	StreamMessages(ctx context.Context, in *StreamMessagesRequest, opts ...grpc.CallOption) (Messaging_StreamMessagesClient, error)
	SendMessages(ctx context.Context, opts ...grpc.CallOption) (Messaging_SendMessagesClient, error)
	Connect(ctx context.Context, opts ...grpc.CallOption) (Messaging_ConnectClient, error)
}

type messagingClient struct {
	cc *grpc.ClientConn
}

func NewMessagingClient(cc *grpc.ClientConn) MessagingClient {
	return &messagingClient{cc}
}

func (c *messagingClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/GetRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) UpdateRoom(ctx context.Context, in *UpdateRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	out := new(Room)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/UpdateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) DeleteRoom(ctx context.Context, in *DeleteRoomRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/DeleteRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) ListRooms(ctx context.Context, in *ListRoomsRequest, opts ...grpc.CallOption) (*ListRoomsResponse, error) {
	out := new(ListRoomsResponse)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/ListRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/UpdateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/ListMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) SearchMessages(ctx context.Context, in *SearchMessagesRequest, opts ...grpc.CallOption) (*longrunning.Operation, error) {
	out := new(longrunning.Operation)
	err := c.cc.Invoke(ctx, "/google.showcase.v1alpha3.Messaging/SearchMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) StreamMessages(ctx context.Context, in *StreamMessagesRequest, opts ...grpc.CallOption) (Messaging_StreamMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messaging_serviceDesc.Streams[0], "/google.showcase.v1alpha3.Messaging/StreamMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagingStreamMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Messaging_StreamMessagesClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type messagingStreamMessagesClient struct {
	grpc.ClientStream
}

func (x *messagingStreamMessagesClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagingClient) SendMessages(ctx context.Context, opts ...grpc.CallOption) (Messaging_SendMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messaging_serviceDesc.Streams[1], "/google.showcase.v1alpha3.Messaging/SendMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagingSendMessagesClient{stream}
	return x, nil
}

type Messaging_SendMessagesClient interface {
	Send(*CreateMessageRequest) error
	CloseAndRecv() (*SendMessagesResponse, error)
	grpc.ClientStream
}

type messagingSendMessagesClient struct {
	grpc.ClientStream
}

func (x *messagingSendMessagesClient) Send(m *CreateMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messagingSendMessagesClient) CloseAndRecv() (*SendMessagesResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendMessagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messagingClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Messaging_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messaging_serviceDesc.Streams[2], "/google.showcase.v1alpha3.Messaging/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &messagingConnectClient{stream}
	return x, nil
}

type Messaging_ConnectClient interface {
	Send(*CreateMessageRequest) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type messagingConnectClient struct {
	grpc.ClientStream
}

func (x *messagingConnectClient) Send(m *CreateMessageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messagingConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessagingServer is the server API for Messaging service.
type MessagingServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*Room, error)
	GetRoom(context.Context, *GetRoomRequest) (*Room, error)
	UpdateRoom(context.Context, *UpdateRoomRequest) (*Room, error)
	DeleteRoom(context.Context, *DeleteRoomRequest) (*empty.Empty, error)
	ListRooms(context.Context, *ListRoomsRequest) (*ListRoomsResponse, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*Message, error)
	GetMessage(context.Context, *GetMessageRequest) (*Message, error)
	UpdateMessage(context.Context, *UpdateMessageRequest) (*Message, error)
	DeleteMessage(context.Context, *DeleteMessageRequest) (*empty.Empty, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesResponse, error)
	SearchMessages(context.Context, *SearchMessagesRequest) (*longrunning.Operation, error)
	StreamMessages(*StreamMessagesRequest, Messaging_StreamMessagesServer) error
	SendMessages(Messaging_SendMessagesServer) error
	Connect(Messaging_ConnectServer) error
}

func RegisterMessagingServer(s *grpc.Server, srv MessagingServer) {
	s.RegisterService(&_Messaging_serviceDesc, srv)
}

func _Messaging_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/GetRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_UpdateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).UpdateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/UpdateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).UpdateRoom(ctx, req.(*UpdateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_DeleteRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).DeleteRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/DeleteRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).DeleteRoom(ctx, req.(*DeleteRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_ListRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).ListRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/ListRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).ListRooms(ctx, req.(*ListRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/UpdateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).UpdateMessage(ctx, req.(*UpdateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/ListMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).ListMessages(ctx, req.(*ListMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_SearchMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).SearchMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.showcase.v1alpha3.Messaging/SearchMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).SearchMessages(ctx, req.(*SearchMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessagingServer).StreamMessages(m, &messagingStreamMessagesServer{stream})
}

type Messaging_StreamMessagesServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type messagingStreamMessagesServer struct {
	grpc.ServerStream
}

func (x *messagingStreamMessagesServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Messaging_SendMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessagingServer).SendMessages(&messagingSendMessagesServer{stream})
}

type Messaging_SendMessagesServer interface {
	SendAndClose(*SendMessagesResponse) error
	Recv() (*CreateMessageRequest, error)
	grpc.ServerStream
}

type messagingSendMessagesServer struct {
	grpc.ServerStream
}

func (x *messagingSendMessagesServer) SendAndClose(m *SendMessagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messagingSendMessagesServer) Recv() (*CreateMessageRequest, error) {
	m := new(CreateMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Messaging_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessagingServer).Connect(&messagingConnectServer{stream})
}

type Messaging_ConnectServer interface {
	Send(*Message) error
	Recv() (*CreateMessageRequest, error)
	grpc.ServerStream
}

type messagingConnectServer struct {
	grpc.ServerStream
}

func (x *messagingConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messagingConnectServer) Recv() (*CreateMessageRequest, error) {
	m := new(CreateMessageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Messaging_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.showcase.v1alpha3.Messaging",
	HandlerType: (*MessagingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _Messaging_CreateRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _Messaging_GetRoom_Handler,
		},
		{
			MethodName: "UpdateRoom",
			Handler:    _Messaging_UpdateRoom_Handler,
		},
		{
			MethodName: "DeleteRoom",
			Handler:    _Messaging_DeleteRoom_Handler,
		},
		{
			MethodName: "ListRooms",
			Handler:    _Messaging_ListRooms_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _Messaging_CreateMessage_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _Messaging_GetMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _Messaging_UpdateMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _Messaging_DeleteMessage_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _Messaging_ListMessages_Handler,
		},
		{
			MethodName: "SearchMessages",
			Handler:    _Messaging_SearchMessages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _Messaging_StreamMessages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendMessages",
			Handler:       _Messaging_SendMessages_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Connect",
			Handler:       _Messaging_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "google/showcase/v1alpha3/messaging.proto",
}

func init() {
	proto.RegisterFile("google/showcase/v1alpha3/messaging.proto", fileDescriptor_14636aef9f8d040f)
}

var fileDescriptor_14636aef9f8d040f = []byte{
	// 1489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcd, 0x6f, 0x1b, 0xc5,
	0x1b, 0xee, 0x38, 0x5f, 0xcd, 0x9b, 0x8f, 0xd6, 0xf3, 0x73, 0xf3, 0x0b, 0x6e, 0x53, 0xd2, 0x0d,
	0x4d, 0x8d, 0xd3, 0xec, 0xb6, 0x6e, 0x44, 0xa5, 0x44, 0x15, 0xda, 0x14, 0x68, 0x2b, 0x35, 0x6d,
	0xb4, 0x69, 0x85, 0xc8, 0xc5, 0x6c, 0xec, 0x89, 0xb3, 0x8a, 0xbd, 0xbb, 0xdd, 0x19, 0x97, 0xa6,
	0x25, 0x08, 0x01, 0x57, 0x10, 0x12, 0x07, 0x0e, 0x88, 0x7f, 0x82, 0x2b, 0x17, 0xc4, 0x91, 0x6b,
	0x39, 0x99, 0x4b, 0x91, 0x38, 0xf5, 0x82, 0xc4, 0x91, 0x03, 0x42, 0x33, 0x3b, 0x6b, 0xef, 0xae,
	0xb3, 0xf6, 0xba, 0x2d, 0x27, 0x7b, 0x67, 0x9f, 0x77, 0xe6, 0x7d, 0x9f, 0x79, 0x3f, 0x1e, 0x1b,
	0x0a, 0x35, 0xc7, 0xa9, 0xd5, 0x89, 0x46, 0xf7, 0x9c, 0x8f, 0x2a, 0x26, 0x25, 0xda, 0xc3, 0xcb,
	0x66, 0xdd, 0xdd, 0x33, 0xaf, 0x68, 0x0d, 0x42, 0xa9, 0x59, 0xb3, 0xec, 0x9a, 0xea, 0x7a, 0x0e,
	0x73, 0xf0, 0xac, 0x8f, 0x54, 0x03, 0xa4, 0x1a, 0x20, 0xf3, 0x67, 0xe4, 0x1e, 0xa6, 0x6b, 0x69,
	0xa6, 0x6d, 0x3b, 0xcc, 0x64, 0x96, 0x63, 0x53, 0xdf, 0x2e, 0xbf, 0x20, 0xdf, 0xd6, 0x1d, 0xbb,
	0xe6, 0x35, 0x6d, 0xdb, 0xb2, 0x6b, 0x9a, 0xe3, 0x12, 0x2f, 0x02, 0x3a, 0x2d, 0x41, 0xe2, 0x69,
	0xa7, 0xb9, 0xab, 0x91, 0x86, 0xcb, 0x0e, 0xe4, 0xcb, 0xf9, 0xf8, 0xcb, 0x5d, 0x8b, 0xd4, 0xab,
	0xe5, 0x86, 0x49, 0xf7, 0x25, 0xe2, 0xf5, 0x38, 0x82, 0x59, 0x0d, 0x42, 0x99, 0xd9, 0x70, 0x25,
	0xe0, 0xac, 0x04, 0x78, 0x6e, 0x45, 0x23, 0x9e, 0xe7, 0x78, 0xe5, 0x2a, 0x61, 0xa6, 0x55, 0x97,
	0xe7, 0x2b, 0x7f, 0x22, 0x18, 0x36, 0x1c, 0xa7, 0x81, 0x0b, 0x30, 0x6c, 0x9b, 0x0d, 0x32, 0x8b,
	0xe6, 0x51, 0x61, 0x7c, 0x3d, 0xf7, 0x5c, 0xcf, 0xc2, 0x09, 0xcf, 0x71, 0x1a, 0x54, 0x7b, 0xc2,
	0x3f, 0xca, 0x56, 0xf5, 0xd0, 0x10, 0x08, 0x7c, 0x0e, 0x26, 0xab, 0x16, 0x75, 0xeb, 0xe6, 0x41,
	0x59, 0x58, 0x64, 0xb8, 0x85, 0x31, 0x21, 0xd7, 0xee, 0x70, 0xc8, 0x3c, 0x4c, 0x54, 0x09, 0xad,
	0x78, 0x96, 0xcb, 0x63, 0x9d, 0x1d, 0x92, 0x88, 0xce, 0x12, 0x5e, 0x83, 0x89, 0x8a, 0x47, 0x4c,
	0x46, 0xca, 0xdc, 0xe3, 0xd9, 0xe1, 0x79, 0x54, 0x98, 0x28, 0xe5, 0x55, 0x49, 0x75, 0x10, 0x8e,
	0x7a, 0x2f, 0x08, 0xc7, 0x00, 0x1f, 0xce, 0x17, 0xb8, 0x71, 0xd3, 0xad, 0xb6, 0x8d, 0x47, 0xfa,
	0x1b, 0xfb, 0x70, 0xbe, 0xa0, 0xdc, 0x80, 0xec, 0x75, 0xb1, 0x15, 0x0f, 0xdb, 0x20, 0x0f, 0x9a,
	0x84, 0x32, 0x5c, 0x82, 0x61, 0x1e, 0xa5, 0x88, 0x7e, 0xa2, 0x74, 0x56, 0x4d, 0xba, 0x72, 0x55,
	0x18, 0x09, 0xac, 0x72, 0x0b, 0xa6, 0x6f, 0x10, 0x16, 0xde, 0xe5, 0x6a, 0x84, 0xc3, 0x85, 0x67,
	0x7a, 0xe6, 0x6f, 0x7d, 0xae, 0xcf, 0x56, 0xdc, 0x40, 0xf9, 0x02, 0x41, 0xf6, 0xbe, 0x70, 0xf1,
	0x25, 0x9d, 0x0a, 0x51, 0xc3, 0xb3, 0x44, 0xdc, 0xcd, 0x51, 0xd4, 0xbc, 0xc7, 0x13, 0x69, 0xc3,
	0xa4, 0xfb, 0x01, 0x35, 0xfc, 0xbb, 0x72, 0x1b, 0xb2, 0xef, 0x90, 0x3a, 0x89, 0x7a, 0xf1, 0xc2,
	0x41, 0xdd, 0x81, 0x93, 0xb7, 0x2d, 0x2a, 0x08, 0xa2, 0xc1, 0x66, 0xa7, 0x61, 0xdc, 0x35, 0x6b,
	0xa4, 0x4c, 0xad, 0xc7, 0xfe, 0x8e, 0x23, 0xc6, 0x71, 0xbe, 0xb0, 0x65, 0x3d, 0x26, 0x78, 0x0e,
	0x40, 0xbc, 0x64, 0xce, 0x3e, 0xb1, 0x65, 0x5a, 0x09, 0xf8, 0x3d, 0xbe, 0xa0, 0x3c, 0x80, 0x6c,
	0x68, 0x3f, 0xea, 0x3a, 0x36, 0x25, 0x78, 0x05, 0x46, 0x44, 0x96, 0xce, 0xa2, 0xf9, 0xa1, 0x14,
	0x24, 0xf9, 0x60, 0xbc, 0x08, 0x27, 0x6c, 0xf2, 0x88, 0x95, 0xbb, 0x8e, 0x9b, 0xe2, 0xcb, 0x9b,
	0xed, 0x23, 0x7f, 0xcf, 0xc0, 0xd8, 0x86, 0x68, 0x07, 0x04, 0xef, 0x46, 0x78, 0x30, 0xfe, 0xd2,
	0xef, 0xe2, 0x37, 0x7a, 0x1e, 0x16, 0x18, 0x5e, 0x48, 0x44, 0x6d, 0x7a, 0xce, 0xae, 0x55, 0x27,
	0x12, 0x28, 0xcb, 0x6b, 0x0d, 0x46, 0xcd, 0x26, 0xdb, 0x73, 0x3c, 0xdf, 0xa5, 0xbe, 0x8c, 0xdf,
	0xa7, 0xc4, 0x33, 0xa4, 0x09, 0xce, 0xc1, 0x30, 0x23, 0x8f, 0x98, 0x5f, 0x71, 0x37, 0x8f, 0x19,
	0xe2, 0x09, 0xcf, 0xc0, 0x88, 0xd5, 0x30, 0x6b, 0x7e, 0x99, 0x4d, 0xde, 0x3c, 0x66, 0xf8, 0x8f,
	0xf1, 0x22, 0x1c, 0x79, 0x99, 0x22, 0x1c, 0x1d, 0xa4, 0x08, 0xd7, 0xc7, 0x61, 0xac, 0xe2, 0xd8,
	0x8c, 0xd8, 0x4c, 0xf9, 0x1a, 0x41, 0xce, 0x2f, 0xc8, 0x80, 0x07, 0x99, 0x2b, 0x6b, 0x30, 0xea,
	0x9a, 0x1e, 0xb1, 0xd9, 0x20, 0xa9, 0x27, 0x4d, 0xf0, 0x1a, 0x8c, 0xf9, 0x7d, 0x9c, 0xc8, 0x1a,
	0x38, 0x97, 0x9c, 0x19, 0xc1, 0xb9, 0x81, 0x85, 0x72, 0x17, 0xb2, 0x37, 0x08, 0x8b, 0xb9, 0xb3,
	0x1a, 0xb9, 0xff, 0x45, 0xe1, 0xcc, 0x7c, 0xdf, 0x3d, 0xfd, 0x52, 0xe0, 0x31, 0xfa, 0xf5, 0xdd,
	0x15, 0x63, 0xdb, 0x4d, 0x34, 0xa8, 0x9b, 0x2f, 0x57, 0xeb, 0x06, 0xe4, 0xfc, 0x5a, 0x7f, 0x85,
	0x61, 0x7e, 0x85, 0xe0, 0x7f, 0xbc, 0x44, 0xe5, 0x2a, 0x7d, 0x25, 0x37, 0x19, 0x69, 0x19, 0x43,
	0x3d, 0x5b, 0xc6, 0x70, 0xbc, 0x65, 0x1c, 0x42, 0x2e, 0xea, 0x8f, 0xec, 0x1a, 0xd7, 0xe0, 0xb8,
	0x24, 0x31, 0x68, 0x1c, 0x29, 0x78, 0x6f, 0x9b, 0xa4, 0x6e, 0x1f, 0x25, 0x38, 0xb5, 0x45, 0x4c,
	0xaf, 0xb2, 0x17, 0x27, 0xe4, 0x35, 0x18, 0x79, 0xd0, 0x24, 0xde, 0x81, 0xe4, 0x63, 0xe8, 0x99,
	0x9e, 0x31, 0xfc, 0x15, 0xe5, 0x0e, 0xcc, 0x44, 0x6d, 0x36, 0x08, 0x33, 0xab, 0x26, 0x33, 0xf1,
	0x0a, 0x80, 0x47, 0x98, 0x77, 0x50, 0xb6, 0xec, 0x5d, 0x47, 0xa6, 0xcb, 0xa9, 0xc0, 0x6d, 0xcf,
	0xad, 0xa8, 0x06, 0x7f, 0x7b, 0xcb, 0xde, 0x75, 0x8c, 0x71, 0x2f, 0xf8, 0xaa, 0xbc, 0x1f, 0xdf,
	0xef, 0x15, 0x91, 0xa0, 0x6c, 0xc2, 0xa9, 0x2d, 0xe6, 0x11, 0xb3, 0x11, 0x0f, 0xee, 0x85, 0x07,
	0xc6, 0x0c, 0xe4, 0xb6, 0x88, 0x5d, 0x8d, 0x3b, 0x5a, 0xfa, 0x32, 0x07, 0xe3, 0x1b, 0x81, 0x28,
	0xc3, 0xdf, 0x23, 0x80, 0xce, 0x00, 0xc7, 0x4b, 0xc9, 0x3e, 0x77, 0x8d, 0xf9, 0x7c, 0x9f, 0xf1,
	0xa0, 0xac, 0xb7, 0xf4, 0xf3, 0x90, 0xe5, 0x33, 0x42, 0x0d, 0x4b, 0x1c, 0x38, 0xe9, 0x2f, 0x75,
	0xf4, 0xcb, 0x67, 0x4f, 0xff, 0xf8, 0x26, 0x93, 0x53, 0x4e, 0x74, 0x54, 0xa3, 0x18, 0x2c, 0xab,
	0xa8, 0x88, 0x3f, 0x81, 0x31, 0x29, 0x0b, 0x70, 0x21, 0xf9, 0xb8, 0xa8, 0x72, 0xe8, 0xeb, 0xd8,
	0x9b, 0x2d, 0x7d, 0xd4, 0xa7, 0x55, 0x9c, 0x9c, 0xc7, 0xb3, 0x9d, 0x93, 0x9f, 0xf0, 0xe5, 0x6b,
	0xbe, 0x56, 0x2b, 0x1e, 0xe2, 0xcf, 0x11, 0x40, 0x47, 0x4b, 0xf4, 0xe2, 0xa7, 0x4b, 0x71, 0xf4,
	0x75, 0xa3, 0x20, 0x4e, 0x57, 0x4a, 0x73, 0xa1, 0xd3, 0x05, 0x35, 0x11, 0x17, 0x38, 0x0b, 0x1f,
	0x03, 0x74, 0xa4, 0x44, 0x2f, 0x27, 0xba, 0x04, 0x47, 0x7e, 0xa6, 0xab, 0x83, 0xbd, 0xcb, 0x35,
	0x71, 0x17, 0x07, 0xc5, 0x64, 0x0e, 0x0e, 0x61, 0xbc, 0x2d, 0x15, 0x70, 0x31, 0xf9, 0xf0, 0xb8,
	0x3e, 0xc9, 0x2f, 0xa5, 0xc2, 0xfa, 0x79, 0xa9, 0xfc, 0x5f, 0xf8, 0x91, 0xc5, 0xf1, 0x2c, 0xc0,
	0xdf, 0x66, 0x60, 0x2a, 0x32, 0xd2, 0xb0, 0xda, 0x2f, 0x4b, 0xa3, 0x5d, 0x38, 0xdf, 0xbf, 0x12,
	0x95, 0x1f, 0x50, 0x4b, 0x5f, 0x0c, 0x1a, 0x2b, 0x4c, 0xca, 0xba, 0x54, 0xf9, 0xc0, 0x87, 0xe9,
	0xe0, 0xc9, 0x97, 0x05, 0x2d, 0xfd, 0x42, 0x1b, 0x38, 0x15, 0xbc, 0x12, 0x12, 0x20, 0x8e, 0x14,
	0x11, 0x7d, 0xa0, 0x2c, 0x84, 0x98, 0xf5, 0xed, 0xda, 0xdc, 0x6a, 0x41, 0x03, 0x58, 0x45, 0xc5,
	0x6d, 0x4d, 0x29, 0x76, 0x01, 0x9b, 0x94, 0x78, 0x54, 0x2b, 0xf2, 0x9f, 0x24, 0x5c, 0xdc, 0x44,
	0x0c, 0xf0, 0x4f, 0x08, 0xa0, 0x33, 0x5a, 0x7b, 0xe5, 0x45, 0xd7, 0x00, 0x4e, 0xc3, 0xc9, 0x4e,
	0x34, 0x45, 0xb6, 0xf0, 0x42, 0x42, 0x8a, 0xb4, 0x9d, 0xd2, 0x8a, 0x87, 0xdb, 0x17, 0x71, 0x31,
	0x86, 0x8a, 0xc5, 0x10, 0x46, 0xe3, 0xa7, 0x08, 0xa6, 0x22, 0xb3, 0xbc, 0xd7, 0xe5, 0x1e, 0x35,
	0xf4, 0xd3, 0x04, 0xe2, 0x08, 0xff, 0xad, 0xd2, 0x52, 0xc8, 0xff, 0xe0, 0xa6, 0x92, 0xe2, 0xe0,
	0x17, 0x72, 0xb5, 0x54, 0x4a, 0x30, 0xe8, 0x11, 0x12, 0xbf, 0x98, 0x1f, 0x11, 0x4c, 0x45, 0xf4,
	0x40, 0xaf, 0xa8, 0x8e, 0x12, 0x0e, 0x89, 0x65, 0x1b, 0xbf, 0x93, 0x62, 0xba, 0x3b, 0x29, 0x0e,
	0x72, 0x27, 0xbf, 0x22, 0x98, 0x0c, 0x0f, 0x7a, 0xbc, 0xdc, 0xbb, 0x8e, 0x63, 0x23, 0x2b, 0xaf,
	0xa6, 0x85, 0xcb, 0xca, 0x27, 0x2d, 0xfd, 0x78, 0x50, 0x51, 0x22, 0xaa, 0x7b, 0x38, 0x4d, 0xc9,
	0x6c, 0x2f, 0xe3, 0xa5, 0xf4, 0xf5, 0x72, 0x88, 0xff, 0x41, 0x30, 0x1d, 0x1d, 0xde, 0x58, 0x4b,
	0xf6, 0xf4, 0x48, 0xa9, 0x91, 0x9f, 0x0b, 0x0c, 0x42, 0x7f, 0x43, 0xa8, 0x77, 0x83, 0xbf, 0x21,
	0x94, 0xef, 0xd0, 0x2f, 0xfa, 0x0e, 0x68, 0xa9, 0x37, 0x95, 0xda, 0x21, 0xad, 0x41, 0x20, 0x5e,
	0x5a, 0xfa, 0x98, 0x94, 0x3c, 0x82, 0xae, 0x45, 0xe5, 0x5c, 0xac, 0x67, 0x6a, 0xcb, 0x9d, 0x3e,
	0x41, 0xc5, 0x16, 0x3c, 0x2b, 0x9f, 0x72, 0x02, 0x22, 0x22, 0xa3, 0x27, 0x01, 0x47, 0xc9, 0x91,
	0x34, 0xd5, 0xb6, 0x2f, 0x9c, 0x22, 0x4a, 0x21, 0x69, 0xa0, 0x84, 0x7c, 0x13, 0x67, 0xf0, 0x52,
	0x7b, 0x4b, 0xb9, 0x3c, 0x40, 0xef, 0x6b, 0xdb, 0x5d, 0x42, 0xf8, 0x37, 0x04, 0x93, 0x61, 0xa1,
	0x33, 0xf0, 0x74, 0x50, 0x7b, 0x25, 0x41, 0xb7, 0x80, 0x52, 0x2c, 0x11, 0x5f, 0x25, 0x12, 0x5f,
	0x62, 0x5b, 0xa7, 0xc4, 0xae, 0xf2, 0xf8, 0x56, 0x14, 0x6d, 0x90, 0xf8, 0x7c, 0xab, 0x02, 0xc2,
	0x1f, 0xc2, 0xd8, 0x75, 0xc7, 0xb6, 0x49, 0x85, 0xfd, 0x07, 0x53, 0xaf, 0x80, 0x2e, 0xa1, 0xf5,
	0x4f, 0x33, 0x3f, 0xeb, 0x2a, 0xbe, 0xb8, 0xc7, 0x98, 0x4b, 0x57, 0x35, 0xad, 0x66, 0xb1, 0xbd,
	0xe6, 0x8e, 0x5a, 0x71, 0x1a, 0x32, 0x2b, 0x4d, 0xd7, 0xa2, 0x5a, 0xcd, 0x74, 0xad, 0xca, 0x72,
	0xb0, 0xd1, 0x73, 0x7d, 0x05, 0xce, 0xc7, 0xfe, 0xce, 0xea, 0x74, 0x90, 0xa0, 0x53, 0xf2, 0x55,
	0x3c, 0x11, 0xfa, 0xed, 0xfe, 0x5c, 0x7f, 0x1b, 0x96, 0xfd, 0xa0, 0x9f, 0xf0, 0x0f, 0x61, 0xd6,
	0xd5, 0x80, 0x22, 0xe6, 0xd3, 0xd1, 0x1f, 0xf5, 0x70, 0xa6, 0xe2, 0x34, 0x12, 0xc3, 0xda, 0x44,
	0xdb, 0x2b, 0x69, 0xdc, 0xd7, 0x28, 0xf1, 0x1e, 0x12, 0x4f, 0xab, 0x11, 0xdb, 0xef, 0xae, 0xa3,
	0xe2, 0xe3, 0xca, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x40, 0x91, 0x48, 0xe2, 0xc6, 0x14, 0x00,
	0x00,
}
